### PR TITLE
readme: add a paragraph how to un-minimize the js shims in the FAQ

### PR DESCRIPTION
**Pull request by emugel**
I think it deserves a mention in the FAQ

### CODE REVIEW

**Comment by kevinresol** [comment]
seems you have accidentally added a unrelated commit

**Comment by emugel** [comment]
damn... I thought i took special care to git reset to be on par with the latest head of lix.pm. I'll have to open my git book when I have some time, still not proficient with those push and PR dance :/

**Comment by emugel** [comment]
Ok I guess I can just close the PR and will open another one

**Comment by emugel** [comment]
(I think this is because I was using my own master branch, then if several PR are issued from the same branch github merges them in the same PR, my bad)

**Pull request closed without merging**
