### PR TITLE
Adding --submodules flag for git

### PR DESCRIPTION
**Pull request by starburst997**
While using git for lime, some commands like `lime rebuild mac` won't works because of missing submodules from the repo. This add a flag that basically call
`git submodule update --init --recursive`

Without submodules, this means we have to include binary blob from git repo for custom branches.

Usage:
`lix install git:git@github.com:starburst997/lime#jd-renderer --submodules`

### CODE REVIEW

**Comment by Aidan63** [comment]
Just a quick comment to say submodule support was what was preventing me from using lix. I've been using your branch for a few weeks now and it works well, so thank you!

**Comment by kevinresol** [comment]
I suppose this should be the default behavior instead of a flag?

**Comment by back2dos** [comment]
Agreed. We should use `--flat` to opt out of recursive cloning.

**Comment by dpomier** [comment]
Maybe this can be merged waiting for another PR to change the default behavior later? It is also preventing my team from using lix :)

**Pull request closed without merging**
