### PR TITLE
better urls

### PR DESCRIPTION
**Pull request by andyli**

### CODE REVIEW

**Comment by nadako** [comment]
pls release a new lix version after merging this! \o/

**Comment by kevinresol** [comment]
15.4.2

**Comment by nadako** [comment]
Thank you Kevin!

**Comment by Gama11** [comment]
Also updated the lix vscode extension.

**Comment by Gama11** [comment]
Um... this may have broken something?

```
>npx lix download
Unable to resolve version 4.0.0-rc.3 locally, install it first with `lix install haxe 4.0.0-rc.3`

>npx lix install haxe 4.0.0-rc.3 
  ... already downloaded!
```

**Comment by Gama11** [comment]
https://raw.githubusercontent.com/HaxeFoundation/haxe.org/staging/downloads/versions.json contains 4.0.0-rc.3, but https://haxe.org/website-content/downloads/versions.json doesn't - this may be related?

**Comment by back2dos** [comment]
Yep, that's where the releases are loaded from. Any idea why the file on haxe.org is behind @andyli ?

**Comment by andyli** [comment]
Fixed in https://github.com/HaxeFoundation/haxe.org/commit/59041b0bc8a33c53d288d3a5c3179f7f79b2e5e2, deploying to haxe.org.

**Comment by back2dos** [comment]
Awesome, thanks ;)

**Pull request merged**
